name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node lockfile
        id: node
        run: |
          if [[ -f package-lock.json || -f npm-shrinkwrap.json || -f yarn.lock ]]; then
            echo "has_node=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_node=false" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/setup-node@v4
        if: steps.node.outputs.has_node == 'true'
        with: { node-version: 'lts/*', cache: 'npm' }

      - run: npm ci
        if: steps.node.outputs.has_node == 'true'

      - run: npm run lint --if-present
        if: steps.node.outputs.has_node == 'true'

      - run: npm test --if-present -- --ci
        if: steps.node.outputs.has_node == 'true'
